/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known/$'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthedAppsNameRouteImport } from './routes/_authed/apps.$name'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppsNameRoute = AuthedAppsNameRouteImport.update({
  id: '/apps/$name',
  path: '/apps/$name',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/apps/$name': typeof AuthedAppsNameRoute
}
export interface FileRoutesByTo {
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof AuthedIndexRoute
  '/apps/$name': typeof AuthedAppsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/apps/$name': typeof AuthedAppsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/login'
    | '/mcp'
    | '/.well-known/$'
    | '/api/$'
    | '/apps/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/consent'
    | '/login'
    | '/mcp'
    | '/.well-known/$'
    | '/api/$'
    | '/'
    | '/apps/$name'
  id:
    | '__root__'
    | '/_authed'
    | '/consent'
    | '/login'
    | '/mcp'
    | '/.well-known/$'
    | '/api/$'
    | '/_authed/'
    | '/_authed/apps/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/apps/$name': {
      id: '/_authed/apps/$name'
      path: '/apps/$name'
      fullPath: '/apps/$name'
      preLoaderRoute: typeof AuthedAppsNameRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAppsNameRoute: typeof AuthedAppsNameRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAppsNameRoute: AuthedAppsNameRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
